services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: todo-migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://todo_user:your_password@postgres:5432/todo_db?sslmode=disable",
        "up",
      ]
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:17
    container_name: todo-postgres

    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: your_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
