// Code generated by MockGen. DO NOT EDIT.
// Source: clients/gemini_client.go
//
// Generated by this command:
//
//	mockgen -source=clients/gemini_client.go -destination=mocks/mock_gemini_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeminiClient is a mock of GeminiClient interface.
type MockGeminiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiClientMockRecorder
	isgomock struct{}
}

// MockGeminiClientMockRecorder is the mock recorder for MockGeminiClient.
type MockGeminiClientMockRecorder struct {
	mock *MockGeminiClient
}

// NewMockGeminiClient creates a new mock instance.
func NewMockGeminiClient(ctrl *gomock.Controller) *MockGeminiClient {
	mock := &MockGeminiClient{ctrl: ctrl}
	mock.recorder = &MockGeminiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiClient) EXPECT() *MockGeminiClientMockRecorder {
	return m.recorder
}

// GenerateDescription mocks base method.
func (m *MockGeminiClient) GenerateDescription(title string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDescription", title)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDescription indicates an expected call of GenerateDescription.
func (mr *MockGeminiClientMockRecorder) GenerateDescription(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDescription", reflect.TypeOf((*MockGeminiClient)(nil).GenerateDescription), title)
}
